### ISSUE TITLE
API Documentation: Error 404

### ISSUE THREAD

**Issue by sphh** [SINTEF/Splipy#149]
The [README](https://github.com/SINTEF/Splipy/blob/master/README.rst) says, that the API documentation can be found at http://sintefmath.github.io/Splipy, but this gives a ‘Site not found’ (404) error.

Where can I find the API documentation online?

**Comment by TheBB** [comment]
Sorry, that snuck through when we migrated from sintefmath to sintef. The correct link now is

https://sintef.github.io/Splipy/

**Comment by sphh** [comment]
Great! Thanks a lot!!
