### ISSUE TITLE
Cannot build with Python 3.10 due to numpy version restriction

### ISSUE THREAD

**Issue by ghost** [SINTEF/Splipy#152]
`setup.py` has:

    install_requires=[
        'numpy    >= 1.15, < 1.20',
        'scipy    >= 1.2',

This prevents splipy from installing with Python 3.10 since the Numpy version that supports Py3.10 is 1.21.  I removed this restriction from `setup.py` (changed to `'numpy    >= 1.15'`) and Splipy seems to build and work just fine.  Can the max. numpy version be bumped up, or removed, from `setup.py`?

**Comment by VikingScientist** [comment]
This is due to #148 to solve an old issue to compile on python 3.6 which I guess is no longer relevant.

I suggest we revoke this requirement now.

**Comment by TheBB** [comment]
Should work now. I'll trigger a new version as well. Hopefully that works well and it'll be out on PyPI later today.

**Comment by ghost** [comment]
I'm afraid that this commit changing the minimum numpy version to 1.20 in setup.py

https://github.com/SINTEF/Splipy/blob/master/setup.py#L26

may be causing this package to be incompatible with many other packages.  I've been maintaining a package for splipy on conda-forge (I'd be happy to turn this over to someone else!) and I've run into some problems with the 1.5.8 release.  Doing `conda install -c conda-forge splipy` causes conda to report `Found conflicts! Looking for incompatible packages` and then spends hours checking.

Is there anything in Splipy which requires features only present in Numpy 1.20?  It would be best to have the minimum version requirement as low as possible, for cross-compatibility with other packages and installations.

**Comment by VikingScientist** [comment]
I am not aware of anything that explicitly requires 1.20, so I imagine that the minimum version could lowered.

**Comment by VikingScientist** [comment]
Nevermind. The follow-up discussions are taking place in #157
