### ISSUE TITLE
Cython build error in ext_modules

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Splipy#155]
#153 introduced a build bug where I cannot build basis_eval.pyx anymore.

```
$ python setup.py build_ext --inplace
running build_ext
error: each element of 'ext_modules' option must be an Extension instance or 2-tuple
```
Reverting `setup.py` to before the pull request gives no errors.

**Comment by TheBB** [comment]
I can't reproduce this... and I barely touched setup.py other than to change the condition on numpy, so not sure what is going on here.

Can you try upgrading, or at least check the version of Cython? I have 0.29.28.

**Comment by VikingScientist** [comment]
Nevermind. This is me messing up with some really old version when I thought that I had rebased on master
