### ISSUE TITLE
Raise splipy's page ranking on PyPI

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Splipy#46]
**Weight:** Occurences of search term weighted by field (name, summary, keywords, description, author, maintainer).

Searching for spline-related keywords does not give splipy a very high ranking on PyPI
* Splipy - instant hit (doesn't even list search results)
* spline - weight 2
* NURBS - (does not appear in list)
* B-spline - (does not appear in list)
* bspline - (does not appear in list)
* modelling - weight 2
*  spline modelling - weight 4

**Comment by VikingScientist** [comment]
[Version 1.2](https://pypi.python.org/pypi/Splipy/1.2.0) published. New metrics is just in:

* NURBS - weight 3
* spline - weight 5
* splines - weight 3
* b-spline (does not appear in list)
* bspline (does not appear in list)
* modelling - weight 2
* spline modelling - weight 7
* curve OR surface OR volume - weight 3

**Comment by TheBB** [comment]
https://github.com/Nachtfeuer/pipeline

> `# (s)hell oriented (p)ipe(line) tool.`
> `pip install spline`

What the…

**Comment by VikingScientist** [comment]
We can probably still do better (still no hit on b-spline?), so I'm keeping this open for now.

**Comment by VikingScientist** [comment]
[The new PyPI now supports Markdown descriptions](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi)

**Comment by VikingScientist** [comment]
Enough marketing for splipy now. I'm closing this.
