### ISSUE TITLE
Not all documentation pages are generated

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Splipy#48]
Clicking the [API Documentation](https://sintefmath.github.io/Splipy/) and then [splipy.utils.refinement](https://sintefmath.github.io/Splipy/utils.html#module-splipy.utils.refinement) or indeed any of the `utils` modules, gives Error 404: site not found

**Comment by VikingScientist** [comment]
I don't get [push_documentation.py](https://github.com/sintefmath/Splipy/blob/master/push_documentation.py) to work. Could you take a look at it. Ideally I would like to only run when `bumpversion` is run (maybe even get it integrated there somehow), but for now feel free to spam this function in order to make it work the way it's supposed to.

**Comment by TheBB** [comment]
Sure I'll look at it.

**Comment by VikingScientist** [comment]
This was fixed by @TheBB
