### ISSUE TITLE
vector multiply bug in cylinder factory function

### ISSUE THREAD

**Issue by prashnts** [SINTEF/Splipy#49]
Hey there,

In cylinder factory, a disk is extruded along an axis as seen here [1]. However, this scaler-to-tuple multiplication is incorrect and hence raises an error for other values of `h`. Instead it should be `(h * i for i in axis)` (or something equivalent).

[1] https://github.com/sintefmath/Splipy/blob/master/splipy/volume_factory.py#L140

**Comment by VikingScientist** [comment]
You are indeed right. Thanks for spotting this.
