### ISSUE TITLE
Python 2 support to be discontinued

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Splipy#70]
[Pip version 10](https://blog.python.org/2018/04/pip-10-has-been-released.html) has been released and to quote the release notes

> * Python 2.6 is no longer supported - if you need pip on Python 2.6, you should stay on pip 9, which is the last version to support Python 2.6.

Seeing as pip is the primary distribution for splipy then I figured that it is time to stop worrying about python 2 and only support python 3 from now on. We will support python 2.6 for release 1.3 and as long as it doesn't require any extra effort to do so, but it is to be expected that release 1.4 will not be python 2 compatible.

**Comment by TheBB** [comment]
I'm all for dropping Python 2 support, but to be clear: the latest version of Python 2 is 2.7. Pip dropping support for 2.6 is not equivalent to dropping support for 2.x.

Are we even running tests on 2.6?

Which reminds me, let's get some CI.

**Comment by TheBB** [comment]
Actually maybe we're running CI internally on Jenkins. I can't recall.

**Comment by VikingScientist** [comment]
Oh... I interpreted this as support for 2.x, not only 2.6. Hm... have to think about it a bit more then, but the fact that nutils does not support 2.x causes some headache if we as a downstream library should support it.

**Comment by TheBB** [comment]
So long as it's an optional dependency, no foul.

**Comment by hugovk** [comment]
Many projects are already making plans for dropping Python 2 (and therefore 2.6 and 2.7) before 2.7 reaches EOL on 2020-01-01.

See:
* https://pythonclock.org
* http://python3statement.org

**Comment by VikingScientist** [comment]
This issue will be closed on January 1st 2020: the official time of death for python 2.
