### ISSUE TITLE
Numpy dependency is weird

### ISSUE THREAD

**Issue by TheBB** [SINTEF/Splipy#85]
So, currently we import numpy in setup.py. This is so that we can get numpy's include directories for compiling a cython module, a module which isn't even being used currently. However the net effect now is that users must install a dependency before pip can even handle the dependencies, which seems backwards.

Another issue is that if numpy *is* installed in a different environment than the user is installing splipy into, the headers may be those of a different version.

I propose we remove the import and the cython build step from setup.py for now, since they are anyway defunct, and revisit at a later date when we can figure out how the #$%^ we can build and distribute a compiled python package without losing our minds.

**Comment by VikingScientist** [comment]
Fixed in #86
